# Generated by Django 5.2 on 2025-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='card_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
